<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="josh-Latitude-3410" failures="1" tests="20" name="testcases.Droppable_Test" time="3.020" errors="0" timestamp="2023-01-24T11:00:16 IST" skipped="0">
  <testcase classname="testcases.Droppable_Test" name="navigate_to_droppable" time="0.181"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="simple_drag_drop" time="0.334"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_simple_drop_successful" time="0.032"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_accept_tab" time="0.130"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_acceptable_drop" time="0.312"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_drag_not_accepted" time="0.045"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="acceptable_drop" time="0.331"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_drag_accepted" time="0.044"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_prevent_propagation_tab" time="0.116"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="greedy_inner_drag_drop" time="0.328"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_greedy_inner_text" time="0.033"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_greedy_outer_text" time="0.019"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_greedy_inner_drop" time="0.306"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_greedy_inner_text" time="0.041"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_greedy_outer_text" time="0.032"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="switch_to_Revert_Draggable_tab" time="0.091"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="revertable_Drag_Drop" time="0.359"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_revertable_drag_successful" time="0.000">
    <failure message="expected [(701, 348)] but found [(451, 302)]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [(701, 348)] but found [(451, 302)]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:643)
at actions.Droppable.verify_revertable_drag_location(Droppable.java:118)
at testcases.Droppable_Test.verify_revertable_drag_successful(Droppable_Test.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </failure>
  </testcase> <!-- verify_revertable_drag_successful -->
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="not_revertable_Drag_Drop" time="0.286"/>
  <system-out/>
  <testcase classname="testcases.Droppable_Test" name="verify_not_revertable_drag_successful" time="0.000"/>
  <system-out/>
</testsuite> <!-- testcases.Droppable_Test -->
